Add files via upload
paoloboychik/RepositoryName2 pull request #3
Opened 2024-01-29 20:45 UTC by paoloboychik

2024-02-05 16:29 UTC, aeksei requested changes
8 из 10 баллов. 

---
Комментарии делятся на следующие категории:
- `GOOD` - хорошее решение. Хорошее или креативное решение.
- `TODO` - можно лучше. Эти замечания не влияют на оценку, и носят рекомендательный характер.
- `FIXME` - необходимо исправить. Устраните эти замечания, чтобы получить максимальный балл. 

---
После проверки работа, может содержать несколько статусов:
- **Changes requested**. Следует выполнить доработки, чтобы получить максимальный балл.  
	Исправление замечаний следует проводить в IDE и приложить согласно инструкции в этот pull request исправленные файлы. Файлы с исправлениями прикладывайте с теми же названиями!
- **Changes approved**. Работа выполнена на максимальный балл.  
	Рекомендуется учесть комментарии рекомендательного характера, и приложить в этот pull request исправленные файлы. В этом случае повторно на проверку присылать работу не нужно. Можно нажимать зеленую кнопку `Merge pull request`.

2024-02-05 16:29 UTC, aeksei commented on Лабораторная 3.py
> +        self._duration = duration
# FIXME

Тут следует присваивать значение свойству `duration`, а не атрибуту `_duration`. Присвоение значения атрибуту не вызовет проверку значения описанную в setter.

B после того как есть сеттер и геттер вне этих методов лучше обращаться через свойства, а не напрямую к атрибутам.

2024-02-05 16:29 UTC, aeksei commented on Лабораторная 3.py
> +        self._pages = pages
# FIXME

Тут следует присваивать значение свойству `pages`, а не атрибуту `_pages`. Присвоение значения атрибуту не вызовет проверку значения описанную в setter.

B после того как есть сеттер и геттер вне этих методов лучше обращаться через свойства, а не напрямую к атрибутам.

2024-02-06 11:45 UTC, merged

2024-02-06 11:53 UTC, paoloboychik commented
fixed